//! Solum crypto layer: **Crypt4GH** envelopes for clinical field categories.
//!
//! Crypt4GH is a universal envelope encryption scheme (X25519 header +
//! ChaCha20-Poly1305 segments). Ferrum uses it for genomic DRS objects; Solum
//! uses the **same format** for clinical category blobs so keys, tooling, and
//! threat models stay aligned across the Synaptic Four portfolio.
//!
//! There is no HL7 “encrypt any FHIR element at rest” standard that replaces
//! this. JWE appears in SMART Health Links / bulk-export *sharing* flows, not
//! as a general at-rest field envelope for compliance layers — see
//! `docs/CRYPTO.md`.
//!
//! ## Customer-held keys
//!
//! Under [`KeyCustody::CustomerHeld`], Solum **never** generates Crypt4GH
//! keypairs. Callers register customer-supplied public (and, for decrypt,
//! private) keys via a [`Crypt4ghKeyProvider`]. Ephemeral in-memory keygen is
//! confined to [`EphemeralTestKeyProvider`] — never for regulated production.
//!
//! ## Honest zero-knowledge path
//!
//! Encrypt/decrypt touch plaintext in process memory. This crate does not
//! claim cryptographic zero-knowledge for those steps.

#![forbid(unsafe_code)]

use std::collections::{HashMap, HashSet};
use std::io::Cursor;

use crypt4gh::keys::{generate_private_key, get_public_key_from_private_key};
use crypt4gh::{decrypt, encrypt, Keys};
use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Git revision pinned in `Cargo.toml` (mirror `config/ci/ferrum-revision.txt`).
pub const FERRUM_GIT_REV: &str = "27a6a8e9a719fd1a171da28b20462a777f95cf65";

/// Upstream repository URL.
pub const FERRUM_GIT_URL: &str = "https://github.com/SynapticFour/Ferrum.git";

/// Envelope algorithm identifier stored on [`EncryptedField`].
pub const ENVELOPE_ALGORITHM: &str = "crypt4gh-v1";

/// Re-export Ferrum shared types for Solum integrators (no logic duplication).
pub use ferrum_core;

/// How encryption keys are held for a deployment.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum KeyCustody {
    /// Keys never leave the customer's HSM / KMS boundary.
    CustomerHeld,
    /// Keys managed by Solum operator on behalf of the customer (restricted).
    OperatorHeld,
    /// Ephemeral / test-only keys — never for regulated production.
    EphemeralTest,
}

/// Declared key-management posture of a running deployment.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct KeyManagementConfig {
    pub custody: KeyCustody,
    /// Optional KMS / HSM provider identifier (e.g. `aws-kms-eu-central-1`).
    pub provider: Option<String>,
}

/// Opaque reference to a customer-held (or test) Crypt4GH keypair.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct KeyRef {
    pub id: String,
}

impl KeyRef {
    pub fn new(id: impl Into<String>) -> Self {
        Self { id: id.into() }
    }
}

/// Serde-serialisable Crypt4GH ciphertext for one clinical field category.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EncryptedField {
    pub category: String,
    pub key_ref: KeyRef,
    pub algorithm: String,
    /// Full Crypt4GH bytes (header + encrypted segments).
    pub ciphertext: Vec<u8>,
}

#[derive(Debug, Error)]
pub enum CryptoError {
    #[error("key custody {actual:?} is not allowed by the active jurisdiction profile (allowed: {allowed:?})")]
    CustodyNotAllowed {
        actual: KeyCustody,
        allowed: Vec<KeyCustody>,
    },
    #[error("field category '{category}' is not in the profile required_field_categories (allowed: {allowed:?})")]
    CategoryNotRecognised {
        category: String,
        allowed: Vec<String>,
    },
    #[error("unknown key reference '{0}'")]
    UnknownKeyRef(String),
    #[error("Crypt4GH encryption failed: {0}")]
    Encrypt(String),
    #[error("Crypt4GH decryption failed (wrong key or tampered ciphertext): {0}")]
    Decrypt(String),
    #[error("invalid Crypt4GH envelope")]
    InvalidEnvelope,
    #[error("key provider refused operation: {0}")]
    Provider(String),
}

/// Resolves Crypt4GH recipient/private keys by [`KeyRef`].
///
/// Solum never mints keys for [`KeyCustody::CustomerHeld`] deployments — the
/// provider only looks up material the customer (or an HSM) supplied.
pub trait Crypt4ghKeyProvider {
    fn recipient_pubkey(&self, key_ref: &KeyRef) -> Result<Vec<u8>, CryptoError>;
    fn private_keys(&self, key_ref: &KeyRef) -> Result<Vec<Keys>, CryptoError>;
}

#[derive(Clone)]
struct HeldKeypair {
    pubkey: Vec<u8>,
    /// 32-byte Crypt4GH private key seed (age-compatible layout as used by crypt4gh-rust).
    privkey: Vec<u8>,
}

/// Customer-held key registry: keypairs are **registered by the customer**,
/// never generated by Solum.
#[derive(Default)]
pub struct CustomerHeldKeyProvider {
    keys: HashMap<String, HeldKeypair>,
}

impl CustomerHeldKeyProvider {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a Crypt4GH keypair that was generated **outside** Solum.
    pub fn register_customer_keypair(
        &mut self,
        key_ref: KeyRef,
        pubkey: Vec<u8>,
        privkey: Vec<u8>,
    ) -> Result<(), CryptoError> {
        if pubkey.is_empty() || privkey.len() < 32 {
            return Err(CryptoError::Provider(
                "customer keypair must include pubkey and >=32-byte privkey".into(),
            ));
        }
        self.keys.insert(
            key_ref.id,
            HeldKeypair {
                pubkey,
                privkey: privkey[..32].to_vec(),
            },
        );
        Ok(())
    }
}

impl Crypt4ghKeyProvider for CustomerHeldKeyProvider {
    fn recipient_pubkey(&self, key_ref: &KeyRef) -> Result<Vec<u8>, CryptoError> {
        self.keys
            .get(&key_ref.id)
            .map(|k| k.pubkey.clone())
            .ok_or_else(|| CryptoError::UnknownKeyRef(key_ref.id.clone()))
    }

    fn private_keys(&self, key_ref: &KeyRef) -> Result<Vec<Keys>, CryptoError> {
        let kp = self
            .keys
            .get(&key_ref.id)
            .ok_or_else(|| CryptoError::UnknownKeyRef(key_ref.id.clone()))?;
        Ok(vec![Keys {
            method: 0,
            privkey: kp.privkey.clone(),
            recipient_pubkey: kp.pubkey.clone(),
        }])
    }
}

/// In-memory Crypt4GH keygen for unit tests and local demos.
///
/// **Never for regulated production** — same posture as [`KeyCustody::EphemeralTest`].
#[derive(Default)]
pub struct EphemeralTestKeyProvider {
    keys: HashMap<String, HeldKeypair>,
}

impl EphemeralTestKeyProvider {
    pub fn new() -> Self {
        Self::default()
    }

    /// Generate and retain a throwaway Crypt4GH keypair. **Test/demo only.**
    pub fn generate_test_keypair(
        &mut self,
        key_ref: KeyRef,
    ) -> Result<(Vec<u8>, Vec<u8>), CryptoError> {
        tracing::warn!(
            key_ref = %key_ref.id,
            "EphemeralTestKeyProvider::generate_test_keypair — never for regulated production"
        );
        let privkey = generate_private_key();
        let pubkey = get_public_key_from_private_key(&privkey)
            .map_err(|e| CryptoError::Provider(e.to_string()))?;
        self.keys.insert(
            key_ref.id,
            HeldKeypair {
                pubkey: pubkey.clone(),
                privkey: privkey.clone(),
            },
        );
        Ok((pubkey, privkey))
    }
}

impl Crypt4ghKeyProvider for EphemeralTestKeyProvider {
    fn recipient_pubkey(&self, key_ref: &KeyRef) -> Result<Vec<u8>, CryptoError> {
        self.keys
            .get(&key_ref.id)
            .map(|k| k.pubkey.clone())
            .ok_or_else(|| CryptoError::UnknownKeyRef(key_ref.id.clone()))
    }

    fn private_keys(&self, key_ref: &KeyRef) -> Result<Vec<Keys>, CryptoError> {
        let kp = self
            .keys
            .get(&key_ref.id)
            .ok_or_else(|| CryptoError::UnknownKeyRef(key_ref.id.clone()))?;
        Ok(vec![Keys {
            method: 0,
            privkey: kp.privkey.clone(),
            recipient_pubkey: kp.pubkey.clone(),
        }])
    }
}

/// Gate that only allows categories listed in a jurisdiction profile's
/// `encryption.required_field_categories`.
#[derive(Debug, Clone, Copy)]
pub struct FieldCategoryGate<'a> {
    required_field_categories: &'a [String],
}

impl<'a> FieldCategoryGate<'a> {
    pub fn new(required_field_categories: &'a [String]) -> Self {
        Self {
            required_field_categories,
        }
    }
}

/// Smoketest that `ferrum-core` symbols resolve at link time.
pub fn ferrum_core_type_name() -> &'static str {
    std::any::type_name::<ferrum_core::FerrumError>()
}

/// Validate that runtime key custody matches what a jurisdiction profile allows.
pub fn validate_key_custody(
    runtime: &KeyManagementConfig,
    allowed: &[KeyCustody],
) -> Result<(), CryptoError> {
    if allowed.iter().any(|c| c == &runtime.custody) {
        Ok(())
    } else {
        Err(CryptoError::CustodyNotAllowed {
            actual: runtime.custody.clone(),
            allowed: allowed.to_vec(),
        })
    }
}

/// Ensure `category` appears in the profile's required encryption categories
/// (same style as `solum_consent::validate_purpose`).
pub fn validate_field_category(
    gate: &FieldCategoryGate<'_>,
    category: &str,
) -> Result<(), CryptoError> {
    if gate.required_field_categories.iter().any(|c| c == category) {
        Ok(())
    } else {
        Err(CryptoError::CategoryNotRecognised {
            category: category.to_string(),
            allowed: gate.required_field_categories.to_vec(),
        })
    }
}

/// Encrypt one clinical field as a Crypt4GH envelope for the recipient pubkey
/// resolved from `key_ref` (same pattern as Ferrum `encrypt_bytes_for_pubkey`).
pub fn encrypt_field(
    gate: &FieldCategoryGate<'_>,
    provider: &impl Crypt4ghKeyProvider,
    category: &str,
    plaintext: &[u8],
    key_ref: &KeyRef,
) -> Result<EncryptedField, CryptoError> {
    validate_field_category(gate, category)?;
    let pubkey = provider.recipient_pubkey(key_ref)?;
    let ciphertext = encrypt_crypt4gh(&pubkey, plaintext)?;
    Ok(EncryptedField {
        category: category.to_string(),
        key_ref: key_ref.clone(),
        algorithm: ENVELOPE_ALGORITHM.to_string(),
        ciphertext,
    })
}

/// Decrypt a Crypt4GH field previously produced by [`encrypt_field`].
pub fn decrypt_field(
    provider: &impl Crypt4ghKeyProvider,
    field: &EncryptedField,
    key_ref: &KeyRef,
) -> Result<Vec<u8>, CryptoError> {
    if field.algorithm != ENVELOPE_ALGORITHM {
        return Err(CryptoError::InvalidEnvelope);
    }
    if key_ref != &field.key_ref {
        return Err(CryptoError::UnknownKeyRef(key_ref.id.clone()));
    }
    let keys = provider.private_keys(key_ref)?;
    decrypt_crypt4gh(&keys, &field.ciphertext)
}

/// Encrypt plaintext for a single recipient public key (Ferrum-compatible).
fn encrypt_crypt4gh(recipient_pubkey: &[u8], plaintext: &[u8]) -> Result<Vec<u8>, CryptoError> {
    let mut keys = HashSet::new();
    keys.insert(recipient_keys_from_pubkey(recipient_pubkey));
    let mut reader = Cursor::new(plaintext.to_vec());
    let mut writer = Vec::new();
    encrypt(&keys, &mut reader, &mut writer, 0, None)
        .map_err(|e| CryptoError::Encrypt(e.to_string()))?;
    Ok(writer)
}

fn decrypt_crypt4gh(keys: &[Keys], ciphertext: &[u8]) -> Result<Vec<u8>, CryptoError> {
    let mut reader = Cursor::new(ciphertext.to_vec());
    let mut writer = Vec::new();
    decrypt(keys, &mut reader, &mut writer, 0, None, &None)
        .map_err(|e| CryptoError::Decrypt(e.to_string()))?;
    Ok(writer)
}

/// Build recipient `Keys` with a fresh ephemeral sender private key — required
/// by crypt4gh-rust for header packets (same lesson as Ferrum).
fn recipient_keys_from_pubkey(pubkey: &[u8]) -> Keys {
    let ephemeral = generate_private_key();
    Keys {
        method: 0,
        privkey: ephemeral[..32].to_vec(),
        recipient_pubkey: pubkey.to_vec(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn load_eu_ehds() -> solum_profiles::JurisdictionProfile {
        solum_profiles::load_profile(
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../config/profiles/eu-ehds.toml"),
        )
        .expect("eu-ehds.toml")
    }

    fn gate_from(profile: &solum_profiles::JurisdictionProfile) -> FieldCategoryGate<'_> {
        FieldCategoryGate::new(&profile.encryption.required_field_categories)
    }

    fn customer_provider_with_fresh_keypair(key_ref: &KeyRef) -> CustomerHeldKeyProvider {
        // Customer generates keys outside Solum; tests simulate that with crypt4gh helpers.
        let privkey = generate_private_key();
        let pubkey = get_public_key_from_private_key(&privkey).unwrap();
        let mut provider = CustomerHeldKeyProvider::new();
        provider
            .register_customer_keypair(key_ref.clone(), pubkey, privkey)
            .unwrap();
        provider
    }

    #[test]
    fn ferrum_core_links() {
        assert!(ferrum_core_type_name().contains("FerrumError"));
    }

    #[test]
    fn customer_held_accepted() {
        let cfg = KeyManagementConfig {
            custody: KeyCustody::CustomerHeld,
            provider: Some("local-hsm".into()),
        };
        assert!(validate_key_custody(&cfg, &[KeyCustody::CustomerHeld]).is_ok());
    }

    #[test]
    fn operator_held_rejected_when_not_allowed() {
        let cfg = KeyManagementConfig {
            custody: KeyCustody::OperatorHeld,
            provider: None,
        };
        assert!(validate_key_custody(&cfg, &[KeyCustody::CustomerHeld]).is_err());
    }

    #[test]
    fn round_trip_encrypt_decrypt_customer_held() {
        let profile = load_eu_ehds();
        let gate = gate_from(&profile);
        let key_ref = KeyRef::new("hsm/slot-1");
        let provider = customer_provider_with_fresh_keypair(&key_ref);

        let plain = b"patient-summary-demo";
        let enc = encrypt_field(&gate, &provider, "patient_summary", plain, &key_ref).unwrap();
        assert_eq!(enc.algorithm, ENVELOPE_ALGORITHM);
        assert_eq!(enc.category, "patient_summary");
        // Crypt4GH magic
        assert!(enc.ciphertext.starts_with(b"crypt4gh"));
        let json = serde_json::to_string(&enc).unwrap();
        let decoded: EncryptedField = serde_json::from_str(&json).unwrap();
        let out = decrypt_field(&provider, &decoded, &key_ref).unwrap();
        assert_eq!(out, plain);
    }

    #[test]
    fn wrong_key_fails_decrypt() {
        let profile = load_eu_ehds();
        let gate = gate_from(&profile);
        let key_ref = KeyRef::new("hsm/slot-1");
        let provider_a = customer_provider_with_fresh_keypair(&key_ref);
        let enc = encrypt_field(&gate, &provider_a, "clinical_notes", b"secret", &key_ref).unwrap();

        let provider_b = customer_provider_with_fresh_keypair(&key_ref);
        let err = decrypt_field(&provider_b, &enc, &key_ref).expect_err("wrong key must fail");
        assert!(matches!(err, CryptoError::Decrypt(_)));
    }

    #[test]
    fn category_outside_profile_rejected() {
        let profile = load_eu_ehds();
        let gate = gate_from(&profile);
        let key_ref = KeyRef::new("hsm/slot-1");
        let provider = customer_provider_with_fresh_keypair(&key_ref);

        let err = encrypt_field(&gate, &provider, "marketing_segment", b"x", &key_ref)
            .expect_err("must reject unknown category");
        assert!(matches!(err, CryptoError::CategoryNotRecognised { .. }));
    }

    #[test]
    fn ephemeral_test_keys_round_trip_with_warning_path() {
        let profile = load_eu_ehds();
        let gate = gate_from(&profile);
        let key_ref = KeyRef::new("ephemeral/test-1");
        let mut provider = EphemeralTestKeyProvider::new();
        provider.generate_test_keypair(key_ref.clone()).unwrap();

        let enc =
            encrypt_field(&gate, &provider, "consent_record", b"consent-v1", &key_ref).unwrap();
        let out = decrypt_field(&provider, &enc, &key_ref).unwrap();
        assert_eq!(out, b"consent-v1");
    }

    #[test]
    fn validate_field_category_mirrors_consent_style() {
        let profile = load_eu_ehds();
        let gate = gate_from(&profile);
        assert!(validate_field_category(&gate, "laboratory_results").is_ok());
        let err = validate_field_category(&gate, "not-a-category").unwrap_err();
        assert!(matches!(err, CryptoError::CategoryNotRecognised { .. }));
    }
}
